name: 'maia-pac'
on:
  push:
    tags:
      - maia-pac-**

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: maia-httpd/maia-pac

jobs:
  publish:
    steps:
    - uses: actions/checkout@v4      
    # this is intended as a temporary workaround, since ubuntu-latest has
    # rust 1.84 and we need 1.85 for the 2024 edition
    - name: Update Rust
      run: rustup update      
    - name: Publish Rust crate
      runs-on: ubuntu-latest
      run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
