name: 'maia-httpd'
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: maia-httpd

jobs:
  armv7:
    name: Rust armv7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Doc
      run: cargo doc
    - name: Install armv7-unknown-linux-gnueabihf Rust target
      run: rustup target add armv7-unknown-linux-gnueabihf
    - name: Install gcc-arm-linux-gnueabihf
      run: |
        sudo apt-get update
        sudo apt-get install gcc-arm-linux-gnueabihf
    - name: Build
      run: |
        cargo build --verbose --target armv7-unknown-linux-gnueabihf \
          --config target.armv7-unknown-linux-gnueabihf.linker=\"arm-linux-gnueabihf-gcc\"
  armv7_cross:
    name: Rust armv7 (with cross)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cross
      run: cargo install cross
    - name: Install armv7-unknown-linux-gnueabihf Rust target
      run: rustup target add armv7-unknown-linux-gnueabihf
    - name: Build
      run: cross build --verbose --target armv7-unknown-linux-gnueabihf
    - name: Run tests
      run: cross test --verbose --target armv7-unknown-linux-gnueabihf
  x86_64:
    name: Rust test x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: cargo test
      run: cargo test --verbose
