name: 'plutosdr-fw'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-fw:
    name: Build Pluto SDR firmware
    runs-on: [self-hosted, vivado]
    steps:
    - name: Checkout plutosdr-fw
      uses: actions/checkout@v4
      with:
        repository: maia-sdr/plutosdr-fw
        submodules: recursive
    - name: Remove maia-sdr submodule
      run: rm -rf maia-sdr
    - name: Checkout maia-sdr
      uses: actions/checkout@v4
      with:
        path: maia-sdr
        # need to fetch history to get the latest tag with git describe
        fetch-depth: 0
        submodules: recursive
    - name: Build firmware
      run: |
        DOCKER_USER="$(id -u):$(id -g)" docker compose run --rm build        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pluto-firmware
        path: |
          build/pluto.dfu
          build/pluto.frm
        if-no-files-found: error
    # The working directory in the self-hosted runner needs be cleaned before
    # building. We use if: ${{ always() }} to clean even if the build fails.
    - name: Clean up runner working dir
      uses: TooMuch4U/actions-clean@v2.1
      if: ${{ always() }}
