name: 'plutosdr-fw-pr-comment'
on:
  workflow_run:
    workflows: ['plutosdr-fw']
    types:
      - completed

jobs:
  pr-comment:
    name: Add PR comment
    needs: build-firmware
    runs-on: ubuntu-latest
    if: $${{ github.event.pull_requests.length > 0 }}
    steps:
    - name: Add comment to PR with link to artifacts
      uses: peter-evans/create-or-update-comment@v2
      with:
        body: |
          The Pluto SDR firmware image for this pull request is ready.
          
          Find it under "Artifacts" in the [action run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}).
        issue-number: ${{ github.event.pull_requests[0].number }}
