name: 'plutosdr-fw'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-fw:
    name: Build Pluto SDR firmware
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/maia-sdr/maia-sdr-devel:latest
      options: --user root
    steps:
    - name: Checkout plutosdr-fw
      uses: actions/checkout@v3
      with:
        repository: maia-sdr/plutosdr-fw
        submodules: recursive
    - name: Remove maia-sdr submodule
      run: rm -rf maia-sdr
    - name: Checkout maia-sdr
      uses: actions/checkout@v3
      with:
        path: maia-sdr
        # need to fetch history to get the latest tag with git describe
        fetch-depth: 0
        submodules: recursive
    - name: Fetch Pluto XSA
      run: |
        cd maia-sdr
        LATEST_TAG=$(git describe --abbrev=0 --tags --exclude '*-prerelease')
        wget -T 3 -t 1 -N http://github.com/maia-sdr/maia-sdr/releases/download/${LATEST_TAG}/pluto_system_top.xsa
    - name: Build firmware
      run: |
        . /opt/rust/env
        export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin/:/usr/bin:/sbin:/bin:/opt/gcc-arm-linux-gnueabi/bin:$PATH:/opt/oss-cad-suite/bin
        export PYTHONPATH=/usr/local/lib/python3.10/dist-packages
        XSA_FILE=maia-sdr/pluto_system_top.xsa make
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pluto-firmware
        path: |
          build/pluto.dfu
          build/pluto.frm
    - name: Delete previous pre-release
      if: github.event_name != 'pull_request'
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: plutosdr-fw-prerelease
        delete_release: true
    - name: Create new pre-release
      if: github.event_name != 'pull_request'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/pluto.dfu
          build/pluto.frm
        name: Maia SDR main branch Pluto SDR firmware (experimental)
        prerelease: true
        tag_name: plutosdr-fw-prerelease
