name: 'plutosdr-fw-pr-comment'
on:
  workflow_run:
    workflows: ['plutosdr-fw']
    types:
      - completed

jobs:
  pr-comment:
    name: Add PR comment
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Get pull_request info
      uses: potiuk/get-workflow-origin@v1_5
      id: workflow-run-info
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        sourceRunId: ${{ github.event.workflow_run.id }}
    - name: Add comment to PR with link to artifacts
      if: github.event.workflow_run.pull_requests[0] != null
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ steps.workflow-run-info.outputs.pullRequestNumber }}
        body: |
          The Pluto SDR firmware image for this pull request is ready.
          
          Find it under "Artifacts" in the [action run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}).
