name: 'plutosdr-fw'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-fw:
    name: Build Pluto SDR firmware
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/maia-sdr/maia-sdr-devel:latest
      options: --user root
    steps:
    - run: echo success